name: Hprofile Actions
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - mail

jobs:
  Testing:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Maven Test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle
